spring:
  application:
    name: trouvetonmatch
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ttm?charSet=UTF8
    username: postgres
    password: postgres
  flyway:
    enabled: true
    baseline-on-migrate: true  # Permet de lancer Flyway même si la base n'est pas vide
    locations: db/migration/data
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
    defer-datasource-initialization: true  # JPA attend la fin de Flyway
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
      enabled: true

  jwt-secret: daf66e01593f61a15b857cf433eee03a005812b31234e149036bbb8dee755dbb
  jwt-expiration-milliseconds: 604800000
logging:
  level:
    root: debug
    org.springframework: debug

debug: true


