spring:
  application:
    name: trouvetonmatch
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ttm?charSet=UTF8
    username: postgres
    password: postgres
  flyway:
    enabled: true
    locations: classpath:db/migration/data
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: none # empeche Hibernate de prendre le dessus sur flyway
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
      enabled: true

  jwt-secret: daf66e01593f61a15b857cf433eee03a005812b31234e149036bbb8dee755dbb
  jwt-expiration-milliseconds: 3600000

  data:
    mongodb:
      uri: mongodb://localhost:27017/?replicaSet=rs0
      db: ttm

#logging:
#  level:
#    root: debug
#    org.springframework: debug

#debug: true

server:
  host: http://localhost:5173
  servlet:
    context-path: /api

