spring:
  application:
    name: trouvetonmatch
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ttm?characterEncoding=UTF8
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
      enabled: true
  flyway:
    enabled: false
    clean-on-validation-error: true
    baseline-on-migrate: true
    locations: db/migration/data

  jwt-secret: daf66e01593f61a15b857cf433eee03a005812b31234e149036bbb8dee755dbb
  jwt-expiration-milliseconds: 604800000
logging:
  level:
    root: debug
    org.springframework: debug

debug: true


