spring:
  application:
    name: trouvetonmatch
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ttm
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  flyway:
    enabled: true
    clean-on-validation-error: true
    baseline-on-migrate: true
    locations: classpath:db/migration/data

  jwt-secret: daf66e01593f61a15b857cf433eee03a005812b31234e149036bbb8dee755dbb
  jwt-expiration-milliseconds: 604800000
logging:
  level:
    root: debug
    org.springframework: debug

debug: true


