spring:
  application:
    name:trouvetonmatch
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ttm?charSet=UTF8
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
  flyway:
    enabled: true
    locations: db/migration/data
    baseline-on-migrate: true

  jwt-secret: daf66e01593f61a15b857cf433eee03a005812b31234e149036bbb8dee755dbb
  jwt-expiration-milliseconds: 604800000

