spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ttm
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: false
    locations: db/migration/data

