name: Validate-pull-request

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  check:
    name: Validation du code
    runs-on: ubuntu-latest
    services:
      db:
        # Image Docker Hub
        image: postgres:16
        # Fournir le mot de passe pour postgres
        env:
          POSTGRES_DB: ttm
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        # Définir les vérifications pour attendre que postgres ait démarré
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Run spring checks
        env:
           SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ttm
           SPRING_DATASOURCE_USERNAME: postgres
           SPRING_DATASOURCE_PASSWORD: postgres
        run: gradle check
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: ./build/test-results/test/
          if-no-files-found: error
          retention-days: 1
          compression-level: 0


